eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url: {http://localhost:8761/eureka/}
  instance:
    hostname: localhost
greeting.message: Hello from common application.yml
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: test
    password: test
