eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url: {http://localhost:8761/eureka/}
  instance:
    hostname: localhost
greeting.message: Good morning from application.yml
spring:
  datasource:
    url: jdbc:mysql://10.10.5.60:3306/dtdc_ctbs_plus
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: dtdc
    password: permit
