eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url: {http://localhost:8761/eureka/}
  instance:
    hostname: localhost
greeting.message: Good morning all
spring:
  cloud:
    config:
      allow-override: false
      override-none: true
      override-system-properties: false
