eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url: {http://localhost:9000/eureka/}
  instance:
    hostname: localhost
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
