eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url: {http://localhost:8761/eureka/}
  instance:
    hostname: localhost
greeting.message: Hello from application.yml in Github
