eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url: {http://localhost:9000/eureka/}
  instance:
    hostname: localhost
greeting.message: Refresh property from github
api.name: push api
